### ISSUE TITLE
Fazer os testes dos modelos no SQLAlchemy

### ISSUE THREAD

**Issue by HelmuthMN** [luantorrex/brazil-covid-analysis#2]
Fazer verificações de integridade dos models de User e Instituicao. 
![image](https://user-images.githubusercontent.com/23724692/136295604-43a4e07c-b730-46d9-8d47-70ab8c69ace1.png)

**Comment by luantorrex** [comment]
Modelos já estão funcionando, informação validada por testes de registro de usuário e instituição
